#ifndef AGR_MALLOCS_H
#define AGR_MALLOCS_H

#define DRIVER_QUEUE_SIZE 10000
#define CARD_BLOCK_SIZE 1024
#define MAX_OPEN_FILES 7
#define IOEXP_PORTA_QUEUE_SIZE 8
#define KEYMGR_MAX_LISTENERS 8

#endif