#ifndef AGR_MALLOCS_H
#define AGR_MALLOCS_H

#define DRIVER_QUEUE_SIZE 20000 //also used for old-style 2612 pcm. must be less than DACSTREAM_BUF_SIZE*DACSTREAM_PRE_COUNT!!
#define DACSTREAM_BUF_SIZE 5000
#define DACSTREAM_PRE_COUNT 16
#define CARD_BLOCK_SIZE 1024
#define MAX_OPEN_FILES 8
#define IOEXP_PORTA_QUEUE_SIZE 8
#define MAX_REALTIME_DATABLOCKS 40
#define FREAD_LOCAL_BUF 512
#define PLAYER_GD3_FIELD_SIZES 128
#define UI_KEYQUEUE_SIZE 16

#endif