#ifndef AGR_MALLOCS_H
#define AGR_MALLOCS_H

#define DRIVER_QUEUE_SIZE 10000
#define DACSTREAM_BUF_SIZE 5000
#define DACSTREAM_PRE_COUNT 16
#define CARD_BLOCK_SIZE 1024
#define MAX_OPEN_FILES 7
#define IOEXP_PORTA_QUEUE_SIZE 8
#define MAX_REALTIME_DATABLOCKS 32
#define FREAD_LOCAL_BUF 512

#endif